version: "3.9"
services:
  server:
    build: ./server-flask
    ports:
      - "5000:5000"
    volumes:
      - ./server:/user/src/app
  web:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/user/src/app
    depends_on:
      - server
